### ISSUE TITLE
VCDS download 404

### ISSUE THREAD

**Issue by crazycori** [cryinkfly/VCDS-VAG-COM-Diagnosis-system-for-Linux#3]
Link in the vcds-install script 404s. At this time, the link is 
https://dltemp.ross-tech.com/VCDS/download/Q83D2F/VCDS-Release-22.9.0-Installer.exe

**Comment by renanrider** [comment]
The url changed, try this:
https://dltemp.ross-tech.com/VCDS/download/Lite120/VCDS-Lite-1.2-Installer.exe

**Comment by cryinkfly** [comment]
It's solved! :)
